version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  deploy-prod:
    working_directory: ~/repo

    docker:
      - image: circleci/node:10.14.2-stretch

    steps:
      - checkout

      - run:
          name: Installing Deployment Dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev g++ build-essential
            sudo pip3 install --upgrade setuptools pytz
            sudo pip3 install awsebcli --upgrade

      - aws-cli/install
      - aws-cli/configure

      - run:
          name: Build
          command: rm yarn.lock; yarn install --network-timeout 1000000

      - run:
          name: Deploy
          command: yarn run deploy

      - run:
          name: Invalidate cache
          command: |
            aws cloudfront create-invalidation \
            --distribution-id E2APV01FSNEH6H \
            --paths "/*"
  deploy-test:
    working_directory: ~/repo

    docker:
      - image: cimg/node:15.4.0

    steps:
      - checkout

      - run:
          name: Installing Deployment Dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev g++ build-essential
            sudo pip3 install --upgrade setuptools pytz
            sudo pip3 install awsebcli --upgrade

      - aws-cli/install
      - aws-cli/configure

      - run:
          name: Build
          command: rm yarn.lock; yarn install --network-timeout 1000000

      - run:
          name: Add env vars
          command: export REACT_APP_API_URL="https://test.covidamp.org/"; export REACT_APP_COVID_LOCAL_URL="https://test.covid-local.org/"

      - run:
          name: Deploy
          command: yarn run deploy-test

      - run:
          name: Invalidate cache
          command: |
            aws cloudfront create-invalidation \
            --distribution-id EZNCMFWHVEZLU \
            --paths "/*"

workflows:
  version: 2
  build:
    jobs:
      - deploy-prod:
          filters:
            branches:
              only:
                - master
      - deploy-test:
          filters:
            branches:
              only:
                - dev
                - dev-not-whole-timeseries
